//! Server-side modules: Axum handlers, shared business logic, MCP handler.

pub mod fn_error;
pub mod functions;

#[cfg(feature = "ssr")]
pub mod agent_sync;
#[cfg(feature = "ssr")]
pub mod api_v2;
#[cfg(feature = "ssr")]
pub mod gap_audit;
#[cfg(feature = "ssr")]
pub mod http_app;
#[cfg(feature = "ssr")]
pub mod m3_analytics;
#[cfg(feature = "ssr")]
pub mod mcp;
#[cfg(feature = "ssr")]
pub mod mcp_premium_tools;
#[cfg(feature = "ssr")]
pub mod mcp_search;
#[cfg(feature = "ssr")]
pub mod mcp_x402;
#[cfg(feature = "ssr")]
pub mod okx_payment;
#[cfg(feature = "ssr")]
pub mod operator_harness;
#[cfg(feature = "ssr")]
pub mod operator_review_transition;
#[cfg(feature = "ssr")]
pub mod product_a;
#[cfg(feature = "ssr")]
pub mod queries;
#[cfg(feature = "ssr")]
pub mod rate_limit;
#[cfg(feature = "ssr")]
pub mod referral_attribution;
#[cfg(feature = "ssr")]
pub mod review_persistence;
pub mod secret_redaction;
#[cfg(feature = "ssr")]
pub mod tool_categories;
#[cfg(feature = "ssr")]
pub mod tool_search;
#[cfg(feature = "ssr")]
pub mod trust_probe_meta;
#[cfg(feature = "ssr")]
pub mod x402_payment;
#[cfg(feature = "ssr")]
pub mod x402_premium;
#[cfg(feature = "ssr")]
pub mod x402_verify;
