- generic [active] [ref=e1]:
  - banner [ref=e2]:
    - link "주 콘텐츠로 건너뛰기" [ref=e3] [cursor=pointer]:
      - /url: "#main"
      - generic [ref=e4]: 주 콘텐츠로 건너뛰기
    - generic [ref=e6]:
      - generic [ref=e8]:
        - button [ref=e9] [cursor=pointer]
        - link "GoDaddy" [ref=e11] [cursor=pointer]:
          - /url: https://venture-redirector.godaddy.com/
          - figure "GoDaddy" [ref=e12]:
            - img [ref=e13]
        - list [ref=e15]:
          - listitem [ref=e16]:
            - link "포트폴리오" [ref=e17] [cursor=pointer]:
              - /url: https://dcc.godaddy.com/control/portfolio
              - generic [ref=e22]: 포트폴리오
          - listitem [ref=e23]:
            - link "DNS" [ref=e24] [cursor=pointer]:
              - /url: https://dcc.godaddy.com/control/dnsmanagement
              - generic [ref=e29]: DNS
          - listitem [ref=e30]:
            - link "이전" [ref=e31] [cursor=pointer]:
              - /url: https://dcc.godaddy.com/control/transfers
              - generic [ref=e36]: 이전
          - listitem [ref=e37]:
            - button "서비스" [ref=e38] [cursor=pointer]:
              - generic [ref=e43]: 서비스
            - list:
              - listitem [ref=e46]:
                - link "DNS 호스팅" [ref=e47] [cursor=pointer]:
                  - /url: https://dcc.godaddy.com/control/dnshosting
                  - generic [ref=e50]: DNS 호스팅
              - listitem [ref=e51]:
                - link "도메인 브로커" [ref=e52] [cursor=pointer]:
                  - /url: https://dbs.godaddy.com
                  - generic [ref=e55]: 도메인 브로커
              - listitem [ref=e56]:
                - link "사전 등록" [ref=e57] [cursor=pointer]:
                  - /url: https://preregistration.godaddy.com
                  - generic [ref=e60]: 사전 등록
              - listitem [ref=e61]:
                - link "블록" [ref=e62] [cursor=pointer]:
                  - /url: https://dcc.godaddy.com/control/blocks
                  - generic [ref=e65]: 블록
              - listitem [ref=e66]:
                - link "협상" [ref=e67] [cursor=pointer]:
                  - /url: https://aftermarket.godaddy.com/negotiations
                  - generic [ref=e70]: 협상
          - listitem [ref=e71]:
            - button "도메인 투자자 센터" [ref=e72] [cursor=pointer]:
              - generic [ref=e77]: 도메인 투자자 센터
            - list:
              - listitem [ref=e80]:
                - link "경매" [ref=e81] [cursor=pointer]:
                  - /url: https://www.auctions.godaddy.com?itc=dcc_portfolio_auctions
                  - generic [ref=e84]: 경매
              - listitem [ref=e85]:
                - link "Afternic" [ref=e86] [cursor=pointer]:
                  - /url: https://sso.godaddy.com/federate/afternic?path=/dashboard/activity?itc=dcc_portfolio_afternic
                  - generic [ref=e89]: Afternic
              - listitem [ref=e90]:
                - link "도메인 파킹" [ref=e91] [cursor=pointer]:
                  - /url: https://www.godaddy.com/domain-parking/dashboard?itc=dcc_portfolio_parking
                  - generic [ref=e94]: 도메인 파킹
              - listitem [ref=e95]:
                - link "도메인 아카데미" [ref=e96] [cursor=pointer]:
                  - /url: https://community.godaddy.com/s/domain-academy?itc=dcc_portfolio_domain_academy
                  - generic [ref=e99]: 도메인 아카데미
              - listitem [ref=e100]:
                - link "대량 검색" [ref=e101] [cursor=pointer]:
                  - /url: https://www.godaddy.com/domains/bulk-domain-search?itc=dcc_portfolio_bulk_search
                  - generic [ref=e104]: 대량 검색
          - listitem [ref=e105]:
            - button "설정" [ref=e106] [cursor=pointer]:
              - generic [ref=e111]: 설정
            - list:
              - listitem [ref=e114]:
                - link "대리인 액세스" [ref=e115] [cursor=pointer]:
                  - /url: https://account.godaddy.com/access
                  - generic [ref=e118]: 대리인 액세스
              - listitem [ref=e119]:
                - link "DNS 템플릿" [ref=e120] [cursor=pointer]:
                  - /url: https://dcc.godaddy.com/control/dns/templates
                  - generic [ref=e123]: DNS 템플릿
              - listitem [ref=e124]:
                - link "내보낸 목록" [ref=e125] [cursor=pointer]:
                  - /url: https://dcc.godaddy.com/control/exported-lists
                  - generic [ref=e128]: 내보낸 목록
          - listitem [ref=e129]:
            - link "활동 로그" [ref=e130] [cursor=pointer]:
              - /url: https://dcc.godaddy.com/control/activity/log
              - generic [ref=e135]: 활동 로그
      - generic [ref=e136]:
        - link "헬프 센터" [ref=e137] [cursor=pointer]:
          - /url: https://www.godaddy.com/help
          - generic [ref=e138]: 헬프 센터
        - button "최근 실행 앱" [ref=e140] [cursor=pointer]
        - button "고객 정보" [ref=e142] [cursor=pointer]:
          - generic [ref=e143]: H
  - main [ref=e145]:
    - generic [ref=e149]:
      - heading "도메인 포트폴리오" [level=1] [ref=e152]
      - navigation [ref=e153]:
        - tablist "Navigation" [ref=e155]:
          - tab "GoDaddy개 도메인" [selected] [ref=e156] [cursor=pointer]
          - tab "외부 도메인 신규" [ref=e157] [cursor=pointer]:
            - text: 외부 도메인
            - generic [ref=e158]: 신규
      - tabpanel "GoDaddy개 도메인" [ref=e159]:
        - generic [ref=e161]:
          - generic [ref=e162]:
            - generic [ref=e165]:
              - combobox "도메인 검색 또는 복사/붙여넣기" [ref=e168]
              - button "도메인 검색" [ref=e169] [cursor=pointer]
            - generic [ref=e170]:
              - combobox "Menu" [ref=e172]:
                - button "Menu Options" [ref=e173] [cursor=pointer]:
                  - button "폴더" [ref=e175]:
                    - generic: 폴더
              - combobox "Menu" [ref=e177]:
                - button "Menu Options" [ref=e178] [cursor=pointer]:
                  - button "프로필" [ref=e180]:
                    - generic: 프로필
              - button "열 편집" [ref=e182] [cursor=pointer]:
                - generic: 열
              - button "인사이트" [ref=e184] [cursor=pointer]:
                - generic: 인사이트
          - generic [ref=e186]:
            - combobox "Menu" [ref=e187]:
              - button "Menu Options" [ref=e188] [cursor=pointer]:
                - generic [ref=e189]: 유형
            - combobox "Menu" [ref=e190]:
              - button "Menu Options" [ref=e191] [cursor=pointer]:
                - generic [ref=e192]: 자동 갱신
            - combobox "Menu" [ref=e193]:
              - button "Menu Options" [ref=e194] [cursor=pointer]:
                - generic [ref=e195]: 잠금
            - combobox "Menu" [ref=e196]:
              - button "Menu Options" [ref=e197] [cursor=pointer]:
                - generic [ref=e198]: 도메인 프라이버시
            - combobox "Menu" [ref=e199]:
              - button "Menu Options" [ref=e200] [cursor=pointer]:
                - generic [ref=e201]: 확장자
            - combobox "Menu" [ref=e202]:
              - button "Menu Options" [ref=e203] [cursor=pointer]:
                - generic [ref=e204]: 만료 날짜
            - combobox "Menu" [ref=e205]:
              - button "Menu Options" [ref=e206] [cursor=pointer]:
                - generic [ref=e207]: 네임서버
            - combobox "Menu" [ref=e208]:
              - button "Menu Options" [ref=e209] [cursor=pointer]:
                - generic [ref=e210]: 자세히
              - text: I I I I I I I I I
          - generic [ref=e213]:
            - generic [ref=e217]:
              - checkbox "도메인 선택" [checked] [ref=e223] [cursor=pointer]
              - generic [ref=e225] [cursor=pointer]:
                - generic "도메인 이름" [ref=e226]:
                  - heading "도메인 이름" [level=5] [ref=e227]
                - button "정렬 기준" [ref=e228]
              - generic [ref=e232]:
                - generic "만료 날짜" [ref=e234]:
                  - heading "만료 날짜" [level=5] [ref=e235]
                - button "정렬 기준" [ref=e236]
              - generic [ref=e239]:
                - generic "자동 갱신" [ref=e241]:
                  - heading "자동 갱신" [level=5] [ref=e242]
                - button "정렬 기준" [ref=e243]
              - generic [ref=e246]:
                - generic [ref=e248]:
                  - button "예상가(USD):" [ref=e250] [cursor=pointer]
                  - generic "예상가" [ref=e251]:
                    - heading "예상가" [level=5] [ref=e252]
                - button "정렬 기준" [ref=e253]
              - generic [ref=e256]:
                - generic "도메인 프라이버시" [ref=e258]:
                  - heading "도메인 프라이버시" [level=5] [ref=e259]
                - button "정렬 기준" [ref=e260]
              - generic [ref=e263]:
                - button "오른쪽으로 표 스크롤" [ref=e264] [cursor=pointer]
                - button "왼쪽으로 표 스크롤" [ref=e266] [cursor=pointer]
            - generic [ref=e270]:
              - img [ref=e272]
              - heading "등록된 도메인 없음" [level=6] [ref=e279]
              - paragraph [ref=e280]:
                - text: 이 계정에 등록된 도메인이 여기에 표시됩니다.
                - button "DNS 호스팅" [ref=e281] [cursor=pointer]:
                  - generic: DNS 호스팅
                - text: 을(를) 추가하여 다른 곳에 등록된 도메인의 DNS 설정을 관리합니다.
              - generic [ref=e283]:
                - button "내 첫 도메인 찾기" [ref=e284] [cursor=pointer]:
                  - generic: 내 첫 도메인 찾기
                - generic [ref=e285]: 또는
                - button "GoDaddy(으)로 도메인 이전하기" [ref=e286] [cursor=pointer]:
                  - generic: GoDaddy(으)로 도메인 이전하기
          - generic [ref=e290]:
            - heading "0 선택됨" [level=5] [ref=e291]
            - button [ref=e292] [cursor=pointer]
  - alert [ref=e293]
  - button "문의하기 문의하기" [ref=e296]:
    - generic [ref=e298] [cursor=pointer]:
      - img "문의하기" [ref=e299]
      - generic [ref=e300]: 문의하기