- generic [ref=e1]:
  - banner [ref=e2]:
    - link "주 콘텐츠로 건너뛰기" [ref=e3] [cursor=pointer]:
      - /url: "#main"
      - generic [ref=e4]: 주 콘텐츠로 건너뛰기
    - generic [ref=e6]:
      - generic [ref=e8]:
        - button [ref=e9] [cursor=pointer]
        - link "GoDaddy" [ref=e10] [cursor=pointer]:
          - /url: https://venture-redirector.godaddy.com/
          - figure "GoDaddy" [ref=e11]:
            - img [ref=e12]
        - list [ref=e14]:
          - listitem [ref=e15]:
            - link "포트폴리오" [ref=e16] [cursor=pointer]:
              - /url: https://dcc.godaddy.com/control/portfolio
              - generic [ref=e21]: 포트폴리오
          - listitem [ref=e22]:
            - link "DNS" [ref=e23] [cursor=pointer]:
              - /url: /control/dnsmanagement
              - generic [ref=e28]: DNS
          - listitem [ref=e29]:
            - link "이전" [ref=e30] [cursor=pointer]:
              - /url: https://dcc.godaddy.com/control/transfers
              - generic [ref=e35]: 이전
          - listitem [ref=e36]:
            - button "서비스" [ref=e37] [cursor=pointer]:
              - generic [ref=e42]: 서비스
            - list:
              - listitem [ref=e45]:
                - link "DNS 호스팅" [ref=e46] [cursor=pointer]:
                  - /url: https://dcc.godaddy.com/control/dnshosting
                  - generic [ref=e49]: DNS 호스팅
              - listitem [ref=e50]:
                - link "도메인 브로커" [ref=e51] [cursor=pointer]:
                  - /url: https://dbs.godaddy.com
                  - generic [ref=e54]: 도메인 브로커
              - listitem [ref=e55]:
                - link "사전 등록" [ref=e56] [cursor=pointer]:
                  - /url: https://preregistration.godaddy.com
                  - generic [ref=e59]: 사전 등록
              - listitem [ref=e60]:
                - link "블록" [ref=e61] [cursor=pointer]:
                  - /url: https://dcc.godaddy.com/control/blocks
                  - generic [ref=e64]: 블록
              - listitem [ref=e65]:
                - link "협상" [ref=e66] [cursor=pointer]:
                  - /url: https://aftermarket.godaddy.com/negotiations
                  - generic [ref=e69]: 협상
          - listitem [ref=e70]:
            - button "도메인 투자자 센터" [ref=e71] [cursor=pointer]:
              - generic [ref=e76]: 도메인 투자자 센터
            - list:
              - listitem [ref=e79]:
                - link "경매" [ref=e80] [cursor=pointer]:
                  - /url: https://www.auctions.godaddy.com?itc=dcc_portfolio_auctions
                  - generic [ref=e83]: 경매
              - listitem [ref=e84]:
                - link "Afternic" [ref=e85] [cursor=pointer]:
                  - /url: https://sso.godaddy.com/federate/afternic?path=/dashboard/activity?itc=dcc_portfolio_afternic
                  - generic [ref=e88]: Afternic
              - listitem [ref=e89]:
                - link "도메인 파킹" [ref=e90] [cursor=pointer]:
                  - /url: https://www.godaddy.com/domain-parking/dashboard?itc=dcc_portfolio_parking
                  - generic [ref=e93]: 도메인 파킹
              - listitem [ref=e94]:
                - link "도메인 아카데미" [ref=e95] [cursor=pointer]:
                  - /url: https://community.godaddy.com/s/domain-academy?itc=dcc_portfolio_domain_academy
                  - generic [ref=e98]: 도메인 아카데미
              - listitem [ref=e99]:
                - link "대량 검색" [ref=e100] [cursor=pointer]:
                  - /url: https://www.godaddy.com/domains/bulk-domain-search?itc=dcc_portfolio_bulk_search
                  - generic [ref=e103]: 대량 검색
          - listitem [ref=e104]:
            - button "설정" [ref=e105] [cursor=pointer]:
              - generic [ref=e110]: 설정
            - list:
              - listitem [ref=e113]:
                - link "대리인 액세스" [ref=e114] [cursor=pointer]:
                  - /url: https://account.godaddy.com/access
                  - generic [ref=e117]: 대리인 액세스
              - listitem [ref=e118]:
                - link "DNS 템플릿" [ref=e119] [cursor=pointer]:
                  - /url: https://dcc.godaddy.com/control/dns/templates
                  - generic [ref=e122]: DNS 템플릿
              - listitem [ref=e123]:
                - link "내보낸 목록" [ref=e124] [cursor=pointer]:
                  - /url: https://dcc.godaddy.com/control/exported-lists
                  - generic [ref=e127]: 내보낸 목록
          - listitem [ref=e128]:
            - link "활동 로그" [ref=e129] [cursor=pointer]:
              - /url: https://dcc.godaddy.com/control/activity/log
              - generic [ref=e134]: 활동 로그
      - generic [ref=e135]:
        - link "헬프 센터" [ref=e136] [cursor=pointer]:
          - /url: https://www.godaddy.com/help
          - generic [ref=e137]: 헬프 센터
        - button "알림" [ref=e174] [cursor=pointer]:
          - generic "알림" [ref=e175]:
            - generic [ref=e179]: "1"
        - button "최근 실행 앱" [ref=e139] [cursor=pointer]
        - button "고객 정보" [ref=e141] [cursor=pointer]:
          - generic [ref=e142]: HL
        - link "카트 비우기" [ref=e195] [cursor=pointer]:
          - /url: https://kr.godaddy.com/pricing
          - generic "카트 비우기" [ref=e196]
  - main [ref=e144]:
    - generic [ref=e148]:
      - heading "DNS 관리" [level=1] [ref=e151]
      - generic [ref=e761]:
        - heading "onchain-ai.xyz" [level=2] [ref=e762]
        - generic [ref=e763]:
          - button "도메인 설정" [ref=e764] [cursor=pointer]:
            - generic: 도메인 설정
          - button "다른 도메인 선택" [ref=e765] [cursor=pointer]:
            - generic: 다른 도메인 선택
      - generic [ref=e198]:
        - navigation [ref=e199]:
          - tablist "Navigation" [ref=e201]:
            - tab "DNS 레코드" [ref=e202] [cursor=pointer]
            - tab "전달" [active] [selected] [ref=e203] [cursor=pointer]
            - tab "네임서버" [ref=e204] [cursor=pointer]
            - tab "호스트 이름" [ref=e205] [cursor=pointer]
            - tab "DNSSEC" [ref=e206] [cursor=pointer]
            - tab "고급" [ref=e207] [cursor=pointer]: 고급
        - tabpanel "전달" [ref=e766]:
          - generic [ref=e767]:
            - generic [ref=e768]:
              - alert [ref=e769]:
                - generic [ref=e773]: 이제 도메인에서 HTTPS를 통한 전달을 사용할 수 있습니다. 포워딩을 설정하거나 편집할 때 도메인에 SSL 인증서가 자동으로 적용되어 도메인의 신뢰성이 향상됩니다. SSL이 활성화되려면 몇 시간이 소요될 수 있습니다.
              - paragraph [ref=e774]:
                - text: 도메인 이름 및/또는 해당 하위 도메인을
                - link "전달" [ref=e775] [cursor=pointer]:
                  - /url: https://www.godaddy.com/help/a-12123?plid=1
                  - generic [ref=e776]: 전달
                - text: 하면 자동으로 방문자를 웹의 다른 위치로 안내할 수 있습니다.
              - generic [ref=e777]:
                - generic [ref=e778]: 도메인
                - button "전달 추가" [ref=e779] [cursor=pointer]:
                  - generic: 전달 추가
              - paragraph [ref=e780]: 설정 안 됨
              - generic [ref=e781]:
                - generic [ref=e782]: 하위 도메인
                - button "전달 추가" [ref=e783] [cursor=pointer]:
                  - generic: 전달 추가
              - paragraph [ref=e784]: 설정 안 됨
              - generic [ref=e786]:
                - table:
                  - rowgroup
            - paragraph [ref=e787]: 선택 사항
            - paragraph [ref=e788]: 도메인을 전달한 후 더 쉽게 공유하고 게시할 수 있도록 긴 URL을 짧고 깔끔한 링크로 바꿀 수 있습니다. 짧은 링크는 일반적으로 몇 분 안에 작동하기 시작하지만 전역적으로 업데이트되는 데 최대 48시간이 걸릴 수 있습니다.
            - button "GoShort GoShort 열기" [ref=e792]:
              - generic [ref=e793]:
                - heading "GoShort" [level=5] [ref=e795]
                - button "GoShort 열기" [disabled] [ref=e796]
        - generic [ref=e428]:
          - img [ref=e430]
          - generic [ref=e494]:
            - generic [ref=e495]: 무료로 소셜 미디어 하위 도메인 설정하기!
            - generic [ref=e496]:
              - text: 귀하의 도메인에는 귀하의 소셜 미디어 페이지에 연결할 수 있는 facebook.onchain-ai.xyz 등의 사용자 정의 가능한 하위 도메인이
              - text: 무료로 제공됩니다.
            - generic [ref=e499]:
              - generic [ref=e500]:
                - generic [ref=e504]: 향상된 SEO
                - generic [ref=e505]: 소셜 하위 도메인은 귀하의 웹사이트가 검색 엔진에서 더 높은 순위를 차지하는 데 도움이 될 수 있습니다.
              - generic [ref=e506]:
                - generic [ref=e510]: 소셜 페이지 홍보하기
                - generic [ref=e512]: facebook.onchain-ai.xyz 등의 소셜 하위 도메인을 방문하는 사람은 누구나 귀하의 소셜 미디어 페이지를 볼 수 있습니다.
              - generic [ref=e513]:
                - generic [ref=e517]: 기본 도메인에 추가하기
                - generic [ref=e519]: 소셜 하위 도메인을 만들어도 현재 onchain-ai.xyz에 연결된 어떤 것에도 영향을 미치지 않습니다.
            - generic [ref=e520]: "시작할 플랫폼 선택:"
            - generic [ref=e521]:
              - button "Instagram" [ref=e522] [cursor=pointer]:
                - generic: Instagram
              - button "Facebook" [ref=e523] [cursor=pointer]:
                - generic: Facebook
              - button "Yelp" [ref=e524] [cursor=pointer]:
                - generic: Yelp
              - button "Google" [ref=e525] [cursor=pointer]:
                - generic: Google
              - button "기타" [ref=e526] [cursor=pointer]:
                - generic: 기타
      - generic [ref=e528]:
        - article [ref=e529]:
          - img "관리형 워드프레스 제품 일러스트" [ref=e531]
          - generic [ref=e532]:
            - generic [ref=e535]: 세밀한 사용자 정의 가능
            - heading "관리형 워드프레스" [level=3] [ref=e536]
            - paragraph [ref=e537]: 워드프레스 사이트를 더 쉽게 만들고, 시작하고, 관리할 수 있도록 개선했습니다.
            - button "플랜 둘러보기" [ref=e538] [cursor=pointer]:
              - text: 플랜 둘러보기
              - img [ref=e539]
        - article [ref=e541]:
          - img "웹 호스팅 제품 일러스트" [ref=e543]
          - generic [ref=e544]:
            - generic [ref=e547]: 고급 사용자
            - heading "웹 호스팅" [level=3] [ref=e548]
            - paragraph [ref=e549]: 개인용 사이트부터 고성능 사이트까지, 믿을 수 있는 웹 호스팅을 경험하세요.
            - button "플랜 둘러보기" [ref=e550] [cursor=pointer]:
              - text: 플랜 둘러보기
              - img [ref=e551]
        - article [ref=e553]:
          - img "웹 디자인 서비스 제품 일러스트" [ref=e555]
          - generic [ref=e556]:
            - generic [ref=e559]: 알아서 처리해드림
            - heading "웹 디자인 서비스" [level=3] [ref=e560]
            - paragraph [ref=e561]: 웹사이트를 구축할 전문가를 채용하여 최대 2.9배 더 많은 웹사이트 트래픽을 얻으세요
            - link "자세히 알아보기" [ref=e562] [cursor=pointer]:
              - /url: https://onboarding.godaddy.com/launch?lid=wsb-vnext-freemat-3&itc=slp_wsb_ft_getstarted_plans_nocc&firstaccess=true
              - text: 자세히 알아보기
              - img [ref=e563]
  - alert [ref=e166]: DNS 관리
  - button "문의하기 문의하기" [ref=e567]:
    - generic [ref=e569] [cursor=pointer]:
      - img "문의하기" [ref=e570]
      - generic [ref=e571]: 문의하기